### ISSUE TITLE
`async` is  keyword in python 3.7

### ISSUE THREAD

**Issue by wydty** [codechenx/bv#2]
```
$ bv -h
Traceback (most recent call last):
  File "/home/q/mconda3/bin/bv", line 7, in <module>
    from bv import bv
  File "/home/q/mconda3/lib/python3.7/site-packages/bv/__init__.py", line 5, in <module>
    from . import vdtui
  File "/home/q/mconda3/lib/python3.7/site-packages/bv/vdtui.py", line 399
    def async(func):
            ^
SyntaxError: invalid syntax
```
`async` is  keyword in python 3.7

**Comment by codechenx** [comment]
bv only support python3.5-3.6 now, I will add the support of python3.7 soon
